### PR TITLE
docker: add ca-certificate for smtp to work

### PR DESCRIPTION
**Pull request by almontasser**

### CODE REVIEW

**Comment by jkdoshi** [comment]
I see you're saying they're needed for SMTP to work. Under what circumstances? I run a local SMTP MTA (exim4) that listens on 172.17.0.1:25 and forwards emails to sendgrid without a problem. Hence asking.

**Comment by pookiepats** [comment]
@jkdoshi will this be merged? 

Your approach wouldn't work inside of Azure VM's (for example) which is where I mostly play so I would really like to see this.

Not only that, the forward step is a bit clunky and could burp under load - why not allow for a method to bypass the extra step if it's legitimate?  

That would be my question.

**Comment by jkdoshi** [comment]
@almontasser sorry for the delay. I think we can certainly add the change you are recommending with this PR. But unfortunately, the file in question (Dockerfile) has had many changes since then. Therefore it is causing merge conflicts.

So can you please pull the latest version, add your change, and then resubmit the PR?

**Comment by almontasser** [comment]
Since the image is being built from the alpine image, the pull request is irrelevant. Alpine already includes a CA-Certificate store.

**Pull request closed without merging**
